{{- if .Values.istio.enabled }}
{{- if or .Values.istio.telemetry.tracing.enabled .Values.istio.telemetry.accessLogging.enabled }}
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: {{ include "istio-config.namespace" . }}
  labels:
    {{- include "istio-config.labels" . | nindent 4 }}
spec:
  {{- if .Values.istio.telemetry.tracing.enabled }}
  tracing:
  - providers:
    - name: "zipkin"
    randomSamplingPercentage: {{ .Values.istio.telemetry.tracing.samplingPercentage }}
  {{- end }}
  {{- if .Values.istio.telemetry.accessLogging.enabled }}
  accessLogging:
  - providers:
    - name: "envoy"
  {{- end }}
{{- end }}
{{- end }}
