apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wealist-infrastructure
  namespace: argocd
spec:
  project: wealist
  source:
    repoURL: https://github.com/OrangesCloud/wealist-argo-helm.git 
    targetRevision: main
    path: main/helm/charts/wealist-infrastructure
    helm:
      valueFiles:
        - values.yaml
        # - values-develop-registry-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-kind-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
