# main/argocd/project.yaml
# 기본 템플릿만 (실제로는 사용 안 함)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wealist
  namespace: argocd
spec:
  description: Wealist Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"  # 기본값만
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"