apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-setup-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.6.1
    helm:
      values: |
        congig:
          preserve: false
        webhookLabels:
          app.kubernetes.io/managed-by: argocd
          #아래는 Kind 환경 전용 스펙
          replicaCount: 1
          admissionController: 
            replicas: 1
          backgroundController:
            replicas: 1
          cleanupController:
            replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNameSpace=true
      - ServerSideApply=true
