#!/bin/bash
# =============================================================================
# Production Config Update Script
# =============================================================================
# Terraform apply 후 설정 파일을 업데이트하는 스크립트
#
# 사용법:
#   ./scripts/prod-update-configs.sh
#
# 사전 요구사항:
#   1. Terraform apply 완료 (terraform/prod/foundation)
#   2. AWS CLI 설정

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 프로젝트 루트 디렉토리
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}Production Config Update Script${NC}"
echo -e "${YELLOW}========================================${NC}"

# Terraform 디렉토리로 이동
cd "$PROJECT_ROOT/terraform/prod/foundation"

# 1. RDS Secret ARN 가져오기
echo -e "\n${BLUE}1. RDS Secret ARN${NC}"
RDS_SECRET_ARN=$(terraform output -raw rds_master_user_secret_arn 2>/dev/null || echo "")
if [ -z "$RDS_SECRET_ARN" ]; then
    echo -e "${RED}Error: rds_master_user_secret_arn not found${NC}"
    echo "Run 'terraform apply' first"
    exit 1
fi

# Secret ID 추출 (arn:aws:secretsmanager:...:secret:<SECRET_ID>)
RDS_SECRET_ID=$(echo "$RDS_SECRET_ARN" | sed 's/.*secret://')
echo -e "RDS Secret ID: ${GREEN}$RDS_SECRET_ID${NC}"

# 2. RDS Host 가져오기
echo -e "\n${BLUE}2. RDS Host${NC}"
RDS_HOST=$(terraform output -raw rds_address 2>/dev/null || echo "")
if [ -z "$RDS_HOST" ]; then
    echo -e "${RED}Error: rds_address not found${NC}"
    exit 1
fi
echo -e "RDS Host: ${GREEN}$RDS_HOST${NC}"

# 3. ECR Registry URL 가져오기
echo -e "\n${BLUE}3. ECR Registry URL${NC}"
ECR_REGISTRY=$(terraform output -raw ecr_registry_url 2>/dev/null || echo "")
if [ -z "$ECR_REGISTRY" ]; then
    echo -e "${RED}Error: ecr_registry_url not found${NC}"
    exit 1
fi
echo -e "ECR Registry: ${GREEN}$ECR_REGISTRY${NC}"

# 4. 동적 관리 확인
echo -e "\n${YELLOW}========================================${NC}"
echo -e "${YELLOW}Dynamic Configuration Status${NC}"
echo -e "${YELLOW}========================================${NC}"

echo -e "\n${GREEN}✓ RDS Secret ID${NC}: 동적 관리됨"
echo -e "   Terraform이 RDS 비밀번호를 고정 경로에 복사:"
echo -e "   ${BLUE}wealist/prod/database/endpoint${NC} (host, username, password)"

echo -e "\n${GREEN}✓ RDS Host${NC}: 동적 관리됨"
echo -e "   ExternalSecret → wealist-shared-secret (DB_HOST)"
echo -e "   db-init Job이 Secret에서 host 가져옴"

echo -e "\n${BLUE}수동 업데이트 필요: prod-registry.yaml${NC}"
echo -e "   Create from template:"
echo -e "   ${YELLOW}cp k8s/helm/environments/prod-registry.example.yaml \\${NC}"
echo -e "   ${YELLOW}   k8s/helm/environments/prod-registry.yaml${NC}"
echo -e "   Then update:"
echo -e "   ${GREEN}imageRegistry: \"$ECR_REGISTRY\"${NC}"

# 5. 자동 업데이트 옵션
echo -e "\n${YELLOW}========================================${NC}"
echo -e "${YELLOW}Auto-update option${NC}"
echo -e "${YELLOW}========================================${NC}"

read -p "Do you want to auto-update prod-registry.yaml? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    REGISTRY_FILE="$PROJECT_ROOT/k8s/helm/environments/prod-registry.yaml"

    cat > "$REGISTRY_FILE" << EOF
# =============================================================================
# Production ECR Registry Configuration
# =============================================================================
# Auto-generated by scripts/prod-update-configs.sh
# Generated at: $(date)

global:
  imageRegistry: "$ECR_REGISTRY"
EOF

    echo -e "${GREEN}Created: $REGISTRY_FILE${NC}"
fi

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Done! Next steps:${NC}"
echo -e "${GREEN}1. Verify prod-registry.yaml is created${NC}"
echo -e "${GREEN}2. Build & push images: ./scripts/prod-build-push.sh${NC}"
echo -e "${GREEN}3. Commit and push to k8s-deploy-prod branch${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "\n${BLUE}Note: RDS Secret ID와 DB Host는 동적으로 관리됩니다.${NC}"
echo -e "${BLUE}Terraform → Secrets Manager → ExternalSecret → K8s Secret${NC}"
